# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UseJavaVersion@0
  inputs:
    versionSpec: '11'

- script: |
    # Commands to build and test your Java application
    ./mvnw clean install  # For Maven
    # Or use './gradlew build' for Gradle
  displayName: 'Build and Test'
